version: "3.1"
services:
  proxy:
    container_name: proxy
    image: nginx
    volumes:
      - ./Services/Reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - update
      - socket
      - auth
      - device

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  db:
    container_name: db
    image: postgres:alpine
    environment:
      POSTGRES_DB: micro
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./Libraries/Database/Init_Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile-auth
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    depends_on:
      - db

  update:
    container_name: update
    build:
      context: .
      dockerfile: Dockerfile-update
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    depends_on:
      - db

  device:
    container_name: device
    build:
      context: .
      dockerfile: Dockerfile-device
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    depends_on:
      - db

  socket:
    container_name: socket
    build:
      context: .
      dockerfile: Dockerfile-socketIO
      args:
        IMAGE: node:slim
    depends_on:
      - db

  broker:
    container_name: broker
    build:
      context: .
      dockerfile: Dockerfile-broker
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    depends_on:
      - redis
      - db
