ARG IMAGE=mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm32v7

FROM $IMAGE AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["./Libraries/Database/Database.csproj", "/Libraries/Database/Database.csproj"]
COPY ["./Libraries/Extensions/Extensions.csproj", "/Libraries/Extensions/Extensions.csproj"]
COPY ["./Services/Authentication/Authentication.csproj", ""]
RUN dotnet restore "./Authentication.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./Services/Authentication/Authentication.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./Services/Authentication/Authentication.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Authentication.dll", "--urls=http://*:5001"]