version: "3.1"
services:
  proxy:
    container_name: proxy
    image: nginx
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - update
      - socket
      - auth
      - device

  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  db:
    container_name: db
    image: postgres:9.6.19-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile-auth
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    expose:
      - 80

  update:
    container_name: update
    build:
      context: .
      dockerfile: Dockerfile-update
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    expose:
      - 80

  device:
    container_name: device
    build:
      context: .
      dockerfile: Dockerfile-device
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    expose:
      - 80

  socket:
    container_name: socket
    build:
      context: .
      dockerfile: Dockerfile-socketIO
      args:
        IMAGE: node:slim
    expose:
      - 80
