version: "3.8"
services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: mysecretpassword
    ports:
      - 8080:80

  db:
    container_name: db
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: micro
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - ./Libraries/Database/Init_Scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile-auth
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    ports:
      - 5001:5001
    depends_on:
      - db

  microcontroller:
    container_name: microcontroller
    build:
      context: .
      dockerfile: Dockerfile-microcontroller
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    ports:
      - 5003:5003
    depends_on:
      - db

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile-backend
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    ports:
      - 5002:5002
    depends_on:
      - db

  socket:
    container_name: socket
    build:
      context: .
      dockerfile: Dockerfile-socketIO
      args:
        IMAGE: node:slim
    depends_on:
      - db
    ports:
      - 3000:3000

  broker:
    container_name: broker
    build:
      context: .
      dockerfile: Dockerfile-broker
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1
    depends_on:
      - redis
      - db
