FROM node:alpine3.12 AS builder

WORKDIR /usr/src/app

COPY ./Services/SocketIO/package*.json .
RUN npm install

FROM arm64v8/node:alpine3.12

WORKDIR /usr/src/app

COPY --from=builder . .

CMD [ "node", "server.js" ]
