ARG IMAGE
FROM $IMAGE AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["./Libraries/Database/Database.csproj", "/Libraries/Database/Database.csproj"]
COPY ["./Libraries/Extensions/Extensions.csproj", "/Libraries/Extensions/Extensions.csproj"]
COPY ["./Services/Broker/Broker.csproj", ""]
RUN dotnet restore "./Broker.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./Services/Broker/Broker.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./Services/Broker/Broker.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Broker.dll"]