ARG IMAGE

FROM node:alpine3.12 AS builder

WORKDIR /usr/src/app

COPY ./Services/SocketIO/package*.json .

RUN npm install

COPY ./Services/SocketIO .

FROM $IMAGE 

WORKDIR /usr/src/app

COPY --from=builder ./usr/src/app .

CMD [ "node", "server.js" ]
