version: '3.1'
services:
  
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432

  adminer:
    image: adminer
    ports:
      - 8080:8080

  auth:
    container_name: auth
    build:
      context: .
      dockerfile: Dockerfile-auth
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1  
    ports:
        - 80:80

  update:
    container_name: update
    build:
      context: .
      dockerfile: Dockerfile-updatedevice
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1  
    ports:
        - 81:80
      
  device:
    container_name: device
    build:
      context: .
      dockerfile: Dockerfile-device
      args:
        IMAGE: mcr.microsoft.com/dotnet/core/aspnet:3.1  
    ports:
        - 82:80