ARG IMAGE=mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim-arm32v7

FROM $IMAGE AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /src
COPY ["./Services/Update/Update.csproj", ""]
RUN dotnet restore "./Update.csproj"
COPY . .
WORKDIR "/src/."
RUN dotnet build "./Services/Update/Update.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "./Services/Update/Update.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Update.dll"]