CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Addresses" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp without time zone NOT NULL,
    "Label" text NULL,
    "IsConfirmed" boolean NOT NULL,
    CONSTRAINT "PK_Addresses" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp without time zone NOT NULL,
    "Name" text NULL,
    "Icon" text NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "FileDatas" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp without time zone NOT NULL,
    "Name" text NULL,
    "Extension" text NULL,
    "Content" bytea NULL,
    CONSTRAINT "PK_FileDatas" PRIMARY KEY ("Id")
);

CREATE TABLE "Kinds" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp without time zone NOT NULL,
    "Name" text NULL,
    "Icon" text NULL,
    CONSTRAINT "PK_Kinds" PRIMARY KEY ("Id")
);

CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Username" text NULL,
    "Created" timestamp without time zone NOT NULL,
    "LastActive" timestamp without time zone NOT NULL,
    "IsActive" boolean NOT NULL,
    "PasswordHash" bytea NULL,
    "PasswordSalt" bytea NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "Registrations" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp without time zone NOT NULL,
    "MacAddressId" integer NOT NULL,
    "BleAddressId" integer NOT NULL,
    "Rssi" integer NOT NULL,
    CONSTRAINT "PK_Registrations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Registrations_Addresses_BleAddressId" FOREIGN KEY ("BleAddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Registrations_Addresses_MacAddressId" FOREIGN KEY ("MacAddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Components" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp without time zone NOT NULL,
    "Name" text NULL,
    "Icon" text NULL,
    "CategoryId" integer NULL,
    CONSTRAINT "PK_Components" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Components_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Versions" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp without time zone NOT NULL,
    "Name" text NULL,
    "Major" smallint NOT NULL,
    "Minor" smallint NOT NULL,
    "Patch" smallint NOT NULL,
    "ComponentId" integer NULL,
    "KindId" integer NULL,
    "FileDataId" integer NOT NULL,
    CONSTRAINT "PK_Versions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Versions_Components_ComponentId" FOREIGN KEY ("ComponentId") REFERENCES "Components" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Versions_FileDatas_FileDataId" FOREIGN KEY ("FileDataId") REFERENCES "FileDatas" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Versions_Kinds_KindId" FOREIGN KEY ("KindId") REFERENCES "Kinds" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "Devices" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Created" timestamp without time zone NOT NULL,
    "Modified" timestamp without time zone NULL,
    "Name" text NULL,
    "Icon" text NULL,
    "AddressId" integer NOT NULL,
    "KindId" integer NULL,
    "CategoryId" integer NULL,
    "ComponentId" integer NULL,
    "VersionId" integer NULL,
    "Updated" timestamp without time zone NULL,
    "IsUpdated" boolean NULL,
    "IsAutoUpdate" boolean NULL,
    CONSTRAINT "PK_Devices" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Devices_Addresses_AddressId" FOREIGN KEY ("AddressId") REFERENCES "Addresses" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Devices_Categories_CategoryId" FOREIGN KEY ("CategoryId") REFERENCES "Categories" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Devices_Components_ComponentId" FOREIGN KEY ("ComponentId") REFERENCES "Components" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Devices_Kinds_KindId" FOREIGN KEY ("KindId") REFERENCES "Kinds" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Devices_Versions_VersionId" FOREIGN KEY ("VersionId") REFERENCES "Versions" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX "IX_Addresses_Label" ON "Addresses" ("Label");

CREATE INDEX "IX_Components_CategoryId" ON "Components" ("CategoryId");

CREATE UNIQUE INDEX "IX_Devices_AddressId" ON "Devices" ("AddressId");

CREATE INDEX "IX_Devices_CategoryId" ON "Devices" ("CategoryId");

CREATE INDEX "IX_Devices_ComponentId" ON "Devices" ("ComponentId");

CREATE INDEX "IX_Devices_KindId" ON "Devices" ("KindId");

CREATE INDEX "IX_Devices_VersionId" ON "Devices" ("VersionId");

CREATE INDEX "IX_Registrations_BleAddressId" ON "Registrations" ("BleAddressId");

CREATE INDEX "IX_Registrations_MacAddressId" ON "Registrations" ("MacAddressId");

CREATE INDEX "IX_Versions_ComponentId" ON "Versions" ("ComponentId");

CREATE INDEX "IX_Versions_FileDataId" ON "Versions" ("FileDataId");

CREATE INDEX "IX_Versions_KindId" ON "Versions" ("KindId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200928171511_InitialMigration', '3.1.4');