name: Docker Build/Publish Image
on:
  push:
    branches: [master]
jobs:
  build-update:
    if: contains(github.event.head_commit.message, '$')
    runs-on: ubuntu-18.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      DOCKER_TARGET_PLATFORM: linux/arm/v7
    steps:
      - name: Checkout the code
        uses: actions/checkout@v1


      - name: Docker Login
        id: docker
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Run Buildx - Authentication (push image)
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$auth'))
        run: |
          docker buildx build --file ./Dockerfile-auth --platform ${{ steps.prepare.outputs.docker_platform }} --tag swierzewskibartosz/service_authentication:latest --output "type=image,push=true" .

      - name: Run Buildx - Backend (push image)
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$backend'))
        run: |
          docker buildx build --file ./Dockerfile-backend --platform ${{ steps.prepare.outputs.docker_platform }} --tag swierzewskibartosz/service_backend:latest --output "type=image,push=true" .

      - name: Run Buildx - Microcontroller (push image)
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$microcontroller'))
        run: |
          docker buildx build --file ./Dockerfile-microcontroller --platform ${{ steps.prepare.outputs.docker_platform }} --tag swierzewskibartosz/service_microcontroller:latest --output "type=image,push=true" .

      - name: Run Buildx - SocketIO (push image)
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$socket'))
        run: |
          docker buildx build --file ./Dockerfile-socketIO --platform ${{ steps.prepare.outputs.docker_platform }} --tag swierzewskibartosz/service_socket_io:latest --output "type=image,push=true" .

      - name: Run Buildx - Broker (push image)
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$broker'))
        run: |
          docker buildx build --file ./Dockerfile-broker --platform ${{ steps.prepare.outputs.docker_platform }} --tag swierzewskibartosz/service_broker:latest --output "type=image,push=true" .

      - name: Run Buildx - Broker Test (push image)
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$br'))
        run: |
          docker build --file ./Dockerfile-broker --tag swierzewskibartosz/broker:latest --output "type=image,push=true" .
