name: Docker Build/Publish Image
on:
  push:
    branches: [master]
jobs:
  build:
    if: contains(github.event.head_commit.message, '$')
    runs-on: ubuntu-18.04
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Docker Login
        id: docker
        if: success()
        run: |
          echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --password-stdin

      - name: Build and push - Authentication
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$auth'))
        run: |
          docker build --file ./Dockerfile-auth --tag swierzewskibartosz/service_authentication:amd --build-arg IMAGE=mcr.microsoft.com/dotnet/aspnet:5.0 .
          docker build --file ./Dockerfile-auth --tag swierzewskibartosz/service_authentication:arm --build-arg IMAGE=mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim-arm32v7 .
          docker push swierzewskibartosz/service_authentication_amd:latest
          docker push swierzewskibartosz/service_authentication_arm:latest

      - name: Run - Backend
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$backend'))
        run: |
          docker build --file ./Dockerfile-backend --tag swierzewskibartosz/service_backend:latest .
          docker push swierzewskibartosz/service_backend:latest

      - name: Run - Microcontroller
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$microcontroller'))
        run: |
          docker build --file ./Dockerfile-microcontroller --tag swierzewskibartosz/service_microcontroller:latest .
          docker push swierzewskibartosz/service_microcontroller:latest

      - name: Run - SocketIO
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$socket'))
        run: |
          docker build --file ./Dockerfile-socketIO --tag swierzewskibartosz/service_socket_io:latest .
          docker push swierzewskibartosz/service_socket_io:latest

      - name: Run - Broker
        if: always() && (contains(github.event.head_commit.message, '$all') || contains(github.event.head_commit.message, '$broker'))
        run: |
          docker build --file ./Dockerfile-broker --tag swierzewskibartosz/service_broker:latest .
          docker push swierzewskibartosz/service_broker:latest
